/**
 * Config File Generator - Creates a new config file from schema defaults
 * and optional user overrides, plus a companion .env file for backward compatibility.
 *
 * Used by the setup script to generate initial configuration,
 * and by the repair flow to regenerate with preserved custom values.
 *
 * @module @shared/config/generate
 */

import * as fs from "fs";
import * as path from "path";
import { stringify as yamlStringify } from "yaml";

import { configSchema } from "./schema";
import { schemaMeta } from "./schema-meta";
import type { ConfigValidationIssue } from "./types";
import { ConfigValidationError } from "./types";

/** Options for generating a config file */
export interface GenerateOptions {
  /** Output format: YAML (default) or JSON */
  format?: "yaml" | "json";
  /** Output path for the generated config file */
  outputPath?: string;
  /** Output path for the companion .env file */
  envOutputPath?: string;
  /** Override values to merge on top of schema defaults */
  overrides?: Record<string, unknown>;
  /** Existing config values to preserve (for repair mode) */
  existingValues?: Record<string, unknown>;
  /** Skip generation of the companion .env file */
  skipEnv?: boolean;
}

/**
 * Generates a new config file with schema defaults and optional overrides.
 *
 * - Applies schema defaults as the base via `configSchema.parse({})`
 * - Overlays `existingValues` for repair mode (preserves user customizations)
 * - Overlays `overrides` for user-provided values (highest priority)
 * - Validates the final config against the schema
 * - Writes to the specified output path in the chosen format
 * - Unless `skipEnv` is true, generates a companion .env file with env var mappings
 *
 * @throws {ConfigValidationError} If the merged config fails schema validation
 */
export function generateConfigFile(options?: GenerateOptions): void {
  const format = options?.format ?? "yaml";
  const outputPath = options?.outputPath ?? path.join(process.cwd(), "llm-toolkit.config.yaml");
  const envOutputPath = options?.envOutputPath ?? path.join(process.cwd(), ".env");
  const skipEnv = options?.skipEnv ?? false;

  // Step 1: Get full default config from schema
  const defaults = configSchema.parse({});

  // Step 2: Deep merge existingValues (repair mode) and overrides onto defaults
  let merged = deepClone(defaults) as Record<string, unknown>;

  if (options?.existingValues) {
    merged = deepMerge(merged, options.existingValues);
  }

  if (options?.overrides) {
    merged = deepMerge(merged, options.overrides);
  }

  // Step 3: Validate the merged config against the schema
  const result = configSchema.safeParse(merged);

  if (!result.success) {
    // Step 4: Report errors to stderr and throw
    const issues: ConfigValidationIssue[] = result.error.issues.map((issue) => ({
      path: issue.path.join("."),
      expected: issue.message,
      received: getValueAtPath(merged, issue.path),
    }));

    const details = issues
      .map((i) => `  - ${i.path}: expected ${i.expected}, got ${JSON.stringify(i.received)}`)
      .join("\n");
    process.stderr.write(`Config validation failed:\n${details}\n`);

    throw new ConfigValidationError(issues);
  }

  const validConfig = result.data;

  // Step 5: Write the config file in the chosen format
  const configContent =
    format === "json"
      ? JSON.stringify(validConfig, null, 2)
      : yamlStringify(validConfig, { indent: 2 });

  // Ensure output directory exists
  const outputDir = path.dirname(outputPath);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  fs.writeFileSync(outputPath, configContent, "utf-8");

  // Step 6: Generate companion .env file unless skipped
  if (!skipEnv) {
    const envContent = generateEnvFileContent(validConfig as Record<string, unknown>);

    const envDir = path.dirname(envOutputPath);
    if (!fs.existsSync(envDir)) {
      fs.mkdirSync(envDir, { recursive: true });
    }

    fs.writeFileSync(envOutputPath, envContent, "utf-8");
  }
}

/**
 * Generates .env file content from a validated config object.
 * Walks schemaMeta for all entries with an `env` property and resolves
 * their values from the config at the corresponding dotted path.
 *
 * @param config - The validated config object
 * @returns .env file content as a string
 */
function generateEnvFileContent(config: Record<string, unknown>): string {
  const lines: string[] = [
    "# LLM Toolkit Environment Variables",
    "# Auto-generated by config generator for backward compatibility",
    "# Edit llm-toolkit.config.yaml instead of this file",
    "",
  ];

  for (const [dottedPath, meta] of Object.entries(schemaMeta)) {
    if (!meta.env) continue;

    const parts = dottedPath.split(".");
    const value = getValueAtPath(config, parts);

    if (value !== undefined && value !== null) {
      lines.push(`${meta.env}=${formatEnvValue(value)}`);
    } else {
      // Write empty value for entries with no resolved value
      lines.push(`${meta.env}=`);
    }
  }

  lines.push(""); // trailing newline
  return lines.join("\n");
}

/**
 * Formats a config value for .env file output.
 * Strings with spaces/special chars are quoted; booleans and numbers are stringified.
 */
function formatEnvValue(value: unknown): string {
  if (typeof value === "string") {
    // Quote strings that contain spaces, #, or quotes
    if (/[\s#"']/.test(value)) {
      return `"${value.replace(/"/g, '\\"')}"`;
    }
    return value;
  }
  if (typeof value === "boolean" || typeof value === "number") {
    return String(value);
  }
  if (Array.isArray(value)) {
    return JSON.stringify(value);
  }
  return String(value);
}

// ─── Utility Helpers ─────────────────────────────────────────────────────────

/**
 * Deep clones a plain object/value (JSON-safe).
 */
function deepClone<T>(value: T): T {
  if (value === null || value === undefined) return value;
  if (typeof value !== "object") return value;
  return JSON.parse(JSON.stringify(value)) as T;
}

/**
 * Deep merges source into target. Source values take precedence.
 * Only merges plain objects recursively; arrays and primitives are replaced.
 */
function deepMerge(
  target: Record<string, unknown>,
  source: Record<string, unknown>,
): Record<string, unknown> {
  const result = { ...target };

  for (const key of Object.keys(source)) {
    const sourceVal = source[key];
    const targetVal = result[key];

    if (isPlainObject(sourceVal) && isPlainObject(targetVal)) {
      result[key] = deepMerge(
        targetVal as Record<string, unknown>,
        sourceVal as Record<string, unknown>,
      );
    } else {
      result[key] = sourceVal;
    }
  }

  return result;
}

/**
 * Checks if a value is a plain object (not array, not null).
 */
function isPlainObject(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

/**
 * Retrieves a value at a given path from a nested object.
 */
function getValueAtPath(obj: unknown, pathParts: (string | number)[]): unknown {
  let current: unknown = obj;
  for (const part of pathParts) {
    if (current === null || current === undefined || typeof current !== "object") {
      return undefined;
    }
    current = (current as Record<string | number, unknown>)[part];
  }
  return current;
}
